---
title: "Untitled"
author: "Svetlana A. Suyazova"
date: '2 апреля 2019 г '
output: html_document
---

```{r}
library('igraph')
library('plotly')
```

```{r}

load('./data/network_data.RData')

G <- upgrade_graph(g)
L <- layout.kamada.kawai(G)

vs <- V(G)
es <- as.data.frame(get.edgelist(G))

Nv <- length(vs)
Ne <- length(es[1]$V1)

Xn <- L[,1]
Yn <- L[,2]

network <- plot_ly(x = ~Xn, y = ~Yn, mode = "markers", text = vs$label, hoverinfo = "text")

edge_shapes <- list()
for(i in 1:Ne) {
  v0 <- es[i,]$V1
  v1 <- es[i,]$V2

  edge_shape = list(
    type = "line",
    line = list(color = "#030303", width = 0.3),
    x0 = Xn[v0],
    y0 = Yn[v0],
    x1 = Xn[v1],
    y1 = Yn[v1]
  )

  edge_shapes[[i]] <- edge_shape
}

axis <- list(title = "", showgrid = FALSE, showticklabels = FALSE, zeroline = FALSE)

p <- layout(
    network,
    title = 'vk.com friends network', 
    shapes = edge_shapes,
    xaxis = axis, 
    yaxis = axis
    )

# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
# chart_link = api_create(p, filename = "vk-network-r")
# chart_link

p
```

